---
Name: goldfinch-component-team
---
Goldfinch\Component\Team\Admin\TeamAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension

---
Name: goldfinch-component-team-icon
Only:
  moduleexists: 'goldfinch/enchantment'
---

Goldfinch\Component\Team\Admin\TeamAdmin:
  menu_icon_class: 'bi-person-badge-fill'

Goldfinch\Component\Team\Pages\Nest\Team:
  icon_class: 'bi-person-badge-fill'

Goldfinch\Component\Team\Blocks\TeamBlock:
  icon: 'bi-person-badge-fill'

